version: '2'

services:
  cli:
    image: php:7.3.0-cli-alpine3.8
    container_name: benchmark-cli
    networks:
      - benchmark
    volumes:
      - .:/code:cached
    env_file:
      - .env
    command: /code/build/container/cli/run.sh
    depends_on:
      - nginx

  nginx:
    image: nginx:1.13-alpine
    container_name: benchmark-nginx
    networks:
      - benchmark
    volumes:
      - .:/code:cached
    ports:
      - "8090:80"
    env_file:
      - .env
    command: /code/build/container/nginx/run.sh
    depends_on:
      - fpm
    logging:
      driver: none

  fpm:
    build: ./
    container_name: benchmark-fpm
    networks:
      - benchmark
    env_file:
      - .env
    command: /code/build/container/fpm/run.sh
    logging:
      driver: none

networks:
  benchmark:
